services:
  postgres:
    image: postgres:17.4-alpine
    container_name: barksys-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      POSTGRES_DB: ${DATABASE_NAME:-barksys}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-root} -d ${DATABASE_NAME:-barksys}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - barksys-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - barksys-network

  migrations:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: migrations
    container_name: barksys-migrations
    restart: 'no'
    env_file:
      - ./api/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - barksys-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    container_name: barksys-api
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - ./api/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - barksys-network

volumes:
  postgres_data:
    driver: local
    name: barksys-postgres-data
  mailpit_data:
    driver: local
    name: barksys-mailpit-data

networks:
  barksys-network:
    driver: bridge
    name: barksys-network
